name: riverpod_lastest
description: A new version flutter_riverpod project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # flutter_riverpod
  flutter_riverpod: ^2.4.6
  # flutter generate
  riverpod_annotation: ^2.3.1
  # equatable
  equatable: ^2.0.5
  json_serializable: ^6.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
  # flutter generate
  build_runner: ^2.4.6   
  riverpod_generator: ^2.3.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  